apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  labels:
    app: data-processor
    component: processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
        component: processing
    spec:
      serviceAccountName: data-pipeline-workload
      containers:
        - name: data-processor
          image: gcr.io/PROJECT_ID/data-processor:latest
          env:
            - name: PROJECT_ID
              value: "PROJECT_ID"
            - name: PUBSUB_SUBSCRIPTION
              value: "user-events-subscription"
            - name: BIGQUERY_DATASET
              value: "logs-dataset"
            - name: BIGQUERY_TABLE
              value: "user-events-table"
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor-service
  labels:
    app: data-processor
spec:
  selector:
    app: data-processor
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
