apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: user-events-topic
  labels:
    component: messaging
    managed-by: config-connector
spec:
  displayName: "User Events Topic"
  kmsKeyName: "projects/secure-gke-gitops-platform/locations/us-central1/keyRings/data-platform-keyring/cryptoKeys/pubsub-encryption-key"
  labels:
    environment: "placeholder"
    team: "data-engineering"
    data-classification: "sensitive"
  messageRetentionDuration: "604800s"  # 7 days
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: data-pipeline-topic
  labels:
    component: messaging
    managed-by: config-connector
spec:
  displayName: "Data Pipeline Topic"
  kmsKeyName: "projects/secure-gke-gitops-platform/locations/us-central1/keyRings/data-platform-keyring/cryptoKeys/pubsub-encryption-key"
  labels:
    environment: "placeholder"
    team: "data-engineering"
    data-classification: "internal"
  messageRetentionDuration: "1209600s"  # 14 days
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: user-events-subscription
  labels:
    component: messaging
    managed-by: config-connector
spec:
  topicRef:
    name: user-events-topic
  ackDeadlineSeconds: 60
  messageRetentionDuration: "604800s"  # 7 days
  retainAckedMessages: false
  enableMessageOrdering: true
  deadLetterPolicy:
    deadLetterTopicRef:
      name: user-events-dlq-topic
    maxDeliveryAttempts: 5
  retryPolicy:
    minimumBackoff: "10s"
    maximumBackoff: "600s"
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: user-events-dlq-topic
  labels:
    component: messaging
    managed-by: config-connector
spec:
  displayName: "User Events Dead Letter Queue"
  kmsKeyName: "projects/secure-gke-gitops-platform/locations/us-central1/keyRings/data-platform-keyring/cryptoKeys/pubsub-encryption-key"
  labels:
    environment: "placeholder"
    team: "data-engineering"
    data-classification: "sensitive"
  messageRetentionDuration: "2592000s"  # 30 days
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: data-pipeline-subscription
  labels:
    component: messaging
    managed-by: config-connector
spec:
  topicRef:
    name: data-pipeline-topic
  ackDeadlineSeconds: 300  # 5 minutes for longer processing
  messageRetentionDuration: "1209600s"  # 14 days
  retainAckedMessages: false
  enableMessageOrdering: false
  retryPolicy:
    minimumBackoff: "10s"
    maximumBackoff: "600s"
