apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-environment

# Reference to base infrastructure
resources:
  - ../../base
  - namespace.yaml
  - project-config.yaml

# Namespace for all resources
namespace: dev

# Environment-specific prefix
namePrefix: ""

# Environment-specific labels
commonLabels:
  environment: "dev"
  team: "data-engineering"

# Environment-specific annotations
commonAnnotations:
  environment: "development"
  managed-by: "config-connector"

# Patches for development-specific configurations
patches:
  # Reduce Pub/Sub message retention for dev  
  - target:
      kind: PubSubTopic
      name: dev-user-events-topic
    patch: |
      - op: replace
        path: /spec/messageRetentionDuration
        value: "259200s"  # 3 days instead of 7
        
  # Reduce storage lifecycle for dev
  - target:
      kind: StorageBucket
      name: dev-data-ingest-bucket
    patch: |
      - op: replace
        path: /spec/lifecycleRule/0/condition/age
        value: 30  # Delete after 30 days
