apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prod-environment

# Reference to base infrastructure
resources:
  - ../../base
  - namespace.yaml
  - project-config.yaml

# Namespace for all resources
namespace: prod

# Environment-specific prefix
namePrefix: ""

# Environment-specific labels
commonLabels:
  environment: "prod"
  team: "data-engineering"

# Environment-specific annotations
commonAnnotations:
  environment: "production"
  managed-by: "config-connector"

# Patches for production-specific configurations
patches:
  # Extended Pub/Sub message retention for production
  - target:
      kind: PubSubTopic
      name: dev-user-events-topic
    patch: |
      - op: replace
        path: /spec/messageRetentionDuration
        value: "1209600s"  # 14 days for production
      - op: replace
        path: /metadata/name
        value: prod-user-events-topic
        
  # Update PubSub subscription to reference the renamed topic
  - target:
      kind: PubSubSubscription
      name: dev-user-events-subscription
    patch: |
      - op: replace
        path: /spec/topicRef/name
        value: prod-user-events-topic
        
  # Production storage - longer lifecycle
  - target:
      kind: StorageBucket
      name: dev-data-ingest-bucket
    patch: |
      - op: replace
        path: /spec/lifecycle/rule/0/condition/age
        value: 365  # 1 year retention
      - op: replace
        path: /metadata/name
        value: prod-data-ingest-bucket
